/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package com.crio.starter;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import springfox.documentation.swagger2.annotations.EnableSwagger2;

@SpringBootApplication
@EnableSwagger2
public class App {

  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }
}
